language: python

python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'

install:
- pip install -e.
script:
- pip install pyflakes
- pyflakes yadageschemas
- yadage-validate madgraph_delphes.yml -t from-github/phenochain

jobs:
  include:
    - stage: deploy
      install:
      - echo none
      script:
      - echo none
      deploy:
        provider: pypi
        on:
          tags: true
        user: "Your username"
        password: "Your password"
