language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
install:
- pip install -e.
script:
- pip install pyflakes
- pyflakes yadageschemas
- yadage-validate madgraph_delphes.yml -t from-github/phenochain

- stage: deploy
  install:
    - echo none
  script:
    - echo none
  deploy:
    provider: pypi
    on:
      tags: true
    username:
      secure: "Ps0viYHqlDlk6SZnQuaIv+sOrerxCznuQyfVa27xFX+1mIov1MeO9E4o7ER377vwI/2RlxIWMCB2gFaTbH2Uk3DDizNxB/HMjwHLgraHoLRxH/vqfEYnwr/zAZdUPzMsMOp50N2TQ41Myb9wjNMobclppjtT7Nzye21cnlj79XTtPwV7v0j1653R/8HL9ETHIC1K/oBFCoWFkTz63XQPA+JmJ93RT/ehaYDJL/YtBZ2mVxTjLUjoRDuDaWvLRVMT7KxZueFSZUd/+kEQ5VDJBGTN7sJ2CAafD3Jka5VAZXKi8MuQM8iazql+dS6iYc8lhJRYzFkaUj6fO80U+vEaxSSN6X6YMs62UQyBZiqKQcwzZL+X//QHFNYh5lw7nOhv9RkwkcVD0HMxVt1l3sVvutGQQQIHKRPOWlWA3DhTDs6Z6oEOKXaQQXhVPw//jJVscbur72PAAJnNNZ5OGUWe6N8HbfTzFporLqr7602cUFJHodSwiFkAb/+onXRvFL3ImfUE9JaYfQuw7XdOmVRkNyPFljgjfBU6KVRSqlp2G0L/3PQGH22yun+W5BaKC3g3JmosfQoZEULJmlc6Q2NlJIBqXRaHmOqQOKG+DVOnTn5a1QfGHU8KfU1ehLBL8wpJrDbIYTq1ZfCuOjKD5AupPjv/Rm4NRqHVj/nZBVcAuUY="
    password:
      secure: "iDaDmw+9DcWU82TVYyA5mM4q96b1K8iOtgE9ZmHdrvar/7JDPTJ1GGZq1ieWliWJ1utNkW1+E9thLGX4+FtwklO3Aeg5mf8rNhSAhyrax+B/Sv4oDomdEZ5Eh5Qq+rYpy2oQ4F67nh3mvUamn/YxtkiLae7H9Gp2LWXM6YLTA0e/1AJHl6Fy/woOGqqeyTJaqlUKw56mlQfnpmysg/GdoWgGsh/Svnew58IsuY0ISqWQ2ekKjwG3qTM1g7faYb0TwYgOu8t2eC6WvuT0SMDTwfiYKcjohT6T0D7hYOso6WTQ7KDfUNoVxMRyu1TioyDJKbHt33w/hxud+L3OWzlek2TwE1Lc/snX0pCLqkIZDBGKWfAopGq19XMdj2JK5imgZ8vVCrxZ6o4fpIimN6eqw4uDOTL2uUAIpRGe1UIPbFl1quC26L+wxgEMO21sEnSvGbRTrytCz/zatVb+ZccIAz7eHKQsdZZ8n3EkXtENYaYH1za5OJKvOY50TGKOGi5fiQAKESzCa+IJ96S3n3PuS78bL6HVQcFMBO6APufDMmGgHw1owaHxypMxsZOIyU6zr+HXjalcoKPP/VMjBIREOMQ760Sa74HgEtwe+nDIzOEukzGhVZhTWxP3zAFTzZdNl90mcBA1XzIE2058Jw5+AwOD+KBiSpT5fXo5Dfcylww="