sudo: required
language: python
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- '3.6'
install:
- pip install pyflakes
- pip install -e .
- pip freeze
script:
- pyflakes .
- yadage-validate madgraph_delphes.yml -t from-github/phenochain
jobs:
- stage: deploy
  deploy:
    provider: pypi
    user:
      secure: Gu7rkUA2V4BGAQYRdQnKAFT/E4Y7X83yx6Iy3Wd0Noy+e3ZU+bbQKtAI7ZFgbe2CAZEnHAuW/54zwvsiQJnqTUUAxZDK/AUbj1AcK7sHVWdJik980AssovdtHLVCpPSEU8K2ikB8xuL8OWmvWzhICW5fkwSoT5wTT583RIR91RF0hh3MBcdpyNMVVZfh7xdP9Tc06H/1Ljm9Fuglutbf+9VCEwp45cHOq$
    password:
      secure: YOl6hTJ9XdFM84ZthqN0+3Zk/nQ23LRNIxMFL4uzKqd6kDB6GLTUmWl+XUu4tzcM4ctgfnL0yyJbqe9YCy+7EWSYMvD2CACQC2Cykd09gn56Aza57F8vRrjTD7AlrPwq9hrF1tzFiuFtM8qvSUr64h3XhUb7KzMVHG6/ZtKZobmNJuaU40dp5N0bqNV38Rnh/n+wwOPKeBaLkOUXCZHWvzk+x7NC++/pN$
    on:
      tags: true
